const DB="wax-vault",STORE="vault",KEY="current";type Record={salt:string;iv:string;cipher:string};
async function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function derive(password:string,salt:Uint8Array){return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:310000,hash:"SHA-256"},await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveKey"]),{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
function b64(x:ArrayBuffer|Uint8Array){return btoa(String.fromCharCode(...new Uint8Array(x)))}function bytes(x:string){return Uint8Array.from(atob(x),c=>c.charCodeAt(0))}
async function raw(){const d=await db();return new Promise<Record|null>((resolve,reject)=>{const r=d.transaction(STORE,"readonly").objectStore(STORE).get(KEY);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error)})}
export async function saveVault(value:unknown,password:string){if(password.length<10)throw new Error("Use a passphrase with at least 10 characters.");const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(password,salt),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,new TextEncoder().encode(JSON.stringify(value)));const d=await db();await new Promise<void>((resolve,reject)=>{const tx=d.transaction(STORE,"readwrite");tx.objectStore(STORE).put({salt:b64(salt),iv:b64(iv),cipher:b64(cipher)},KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function loadVault(password:string){const record=await raw();if(!record)throw new Error("No encrypted vault found on this device.");try{const key=await derive(password,bytes(record.salt));const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:bytes(record.iv)},key,bytes(record.cipher));return JSON.parse(new TextDecoder().decode(plain))}catch{throw new Error("Incorrect passphrase or corrupted vault.")}}
export async function exportVault(){const record=await raw();if(!record)throw new Error("No encrypted vault found.");return JSON.stringify({format:"wax-vault-aes-gcm-v1",record},null,2)}
export async function importVault(json:string){const parsed=JSON.parse(json);if(parsed.format!=="wax-vault-aes-gcm-v1"||!parsed.record?.cipher)throw new Error("Invalid encrypted vault export.");const d=await db();await new Promise<void>((resolve,reject)=>{const tx=d.transaction(STORE,"readwrite");tx.objectStore(STORE).put(parsed.record,KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function hasVault(){return!!(await raw())}
