import React from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Divider, Grid, IconButton, Skeleton, Stack, Tooltip, Typography } from "@mui/material";
import { ExploreOutlined, FavoriteBorder, Refresh, SettingsOutlined, TrendingUp, Visibility, VisibilityOff } from "@mui/icons-material";
import { Link } from "react-router-dom";
import { useDashboardStore } from "../application/dashboard-store-v2";
import { SUPPORTED_DAPPS, useFavoriteDappStore } from "../application/favorite-dapp-store";

export function DashboardScreen() {
  const { account, balances, history, nfts, loading, error, refresh, isTokenHidden, toggleTokenVisibility } = useDashboardStore();
  const { favoriteUrls } = useFavoriteDappStore();
  const visibleBalances = balances.filter((token: any) => !isTokenHidden(token));
  const favoriteApps = SUPPORTED_DAPPS.filter((dapp) => favoriteUrls.includes(dapp.url)).slice(0, 3);
  const theme = localStorage.getItem("wax-theme") === "dark" ? "Dark" : "Light";
  const locale = (localStorage.getItem("wax-locale") || "en").toUpperCase();
  const rpc = localStorage.getItem("wax-rpc") || "https://wax.greymass.com";

  return <Stack spacing={3}>
    <Card sx={{ background: "linear-gradient(135deg, #17130a, #b8860b)", color: "white" }}><CardContent><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" spacing={2}><Box><Typography variant="overline" sx={{ letterSpacing: 1.8, opacity: .9 }}>Portfolio overview</Typography><Typography variant="h4" fontWeight={800}>{account || "Connect a WAX account"}</Typography><Typography sx={{ opacity: .85 }}>Non-custodial assets, WAX tools, and connected dApp activity.</Typography></Box><Button variant="contained" color="inherit" startIcon={<Refresh />} onClick={() => refresh()} disabled={loading} sx={{ color: "#4938b5", alignSelf: "center", fontWeight: 700 }}>{loading ? "Refreshing…" : "Refresh"}</Button></Stack></CardContent></Card>
    {!account && <Alert severity="info">Verify or connect a WAX account to unlock your wallet and token activity.</Alert>}
    <Grid container spacing={3}>
      <Grid item xs={12} md={4}><Card sx={{ height: "100%" }}><CardContent><Stack spacing={2}><Stack direction="row" alignItems="center" justifyContent="space-between"><Stack direction="row" spacing={1} alignItems="center"><FavoriteBorder color="primary" /><Typography variant="h6">Favorites</Typography></Stack><Button component={Link} to="/favorites" size="small">Manage</Button></Stack>{favoriteApps.length ? favoriteApps.map((dapp) => <Stack key={dapp.url} direction="row" alignItems="center" justifyContent="space-between" sx={{ border: 1, borderColor: "divider", borderRadius: 2, px: 1.5, py: 1 }}><Box><Typography fontWeight={700}>{dapp.name}</Typography><Typography variant="caption" color="text.secondary">{dapp.description}</Typography></Box><Button component="a" href={dapp.url} target="_blank" rel="noreferrer" size="small" variant="outlined">Open</Button></Stack>) : <Typography color="text.secondary">No favorite dApps yet. Save trusted WAX destinations.</Typography>}</Stack></CardContent></Card></Grid>
      <Grid item xs={12} md={4}><Card sx={{ height: "100%" }}><CardContent><Stack spacing={2}><Stack direction="row" alignItems="center" justifyContent="space-between"><Stack direction="row" spacing={1} alignItems="center"><ExploreOutlined color="primary" /><Typography variant="h6">Explorer</Typography></Stack><Button component={Link} to="/explorer" size="small">View</Button></Stack><Box sx={{ bgcolor: "primary.main", color: "white", borderRadius: 2, p: 1.5 }}><Typography variant="caption" sx={{ opacity: .9 }}>Network</Typography><Typography variant="h6" fontWeight={700}>WAX ready</Typography></Box><Stack spacing={1}><Chip label="WAXBlock" size="small" /><Chip label="AtomicHub" size="small" /><Chip label="Alcor" size="small" /></Stack><Typography variant="body2" color="text.secondary">Check account permissions, network health, and ecosystem dApps before approving transactions.</Typography></Stack></CardContent></Card></Grid>
      <Grid item xs={12} md={4}><Card sx={{ height: "100%" }}><CardContent><Stack spacing={2}><Stack direction="row" alignItems="center" justifyContent="space-between"><Stack direction="row" spacing={1} alignItems="center"><SettingsOutlined color="primary" /><Typography variant="h6">Settings</Typography></Stack><Button component={Link} to="/settings" size="small">Open</Button></Stack><Stack spacing={1}><Typography variant="body2" color="text.secondary">Theme: {theme}</Typography><Typography variant="body2" color="text.secondary">Locale: {locale}</Typography><Typography variant="body2" color="text.secondary" noWrap>RPC: {rpc}</Typography></Stack><Divider /><Button variant="contained" component={Link} to="/settings">Review wallet settings</Button></Stack></CardContent></Card></Grid>
    </Grid>
    {error && <Alert severity="error">{error}</Alert>}
    <Grid container spacing={2}>{(loading ? [1, 2, 3, 4] : visibleBalances).map((token: any, index: number) => <Grid item xs={12} sm={6} md={3} key={token?.symbol ?? index}><Card variant="outlined" sx={{ height: "100%" }}><CardContent>{loading ? <Skeleton height={72} /> : <><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography fontWeight={700}>{token.icon ?? "◈"} {token.symbol}</Typography><Tooltip title={isTokenHidden(token) ? "Show token" : "Hide token"}><IconButton size="small" onClick={() => toggleTokenVisibility(token)}>{isTokenHidden(token) ? <VisibilityOff /> : <Visibility />}</IconButton></Tooltip></Stack><Typography variant="h5" sx={{ mt: 2 }}>{token.balance}</Typography><Typography variant="caption" color="text.secondary">{token.name ?? token.contract}</Typography></>}</CardContent></Card></Grid>)}</Grid>
    {!loading && balances.length > 0 && visibleBalances.length === 0 && <Alert severity="info">All tokens are hidden. Open Assets and choose “Show all tokens” to restore them.</Alert>}
    <Grid container spacing={2}><Grid item xs={12} md={7}><Card><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h6">Activity stream</Typography><TrendingUp color="primary" /></Stack><Stack spacing={1.5} sx={{ mt: 2 }}>{history.length ? history.slice(0, 8).map((item: any, index: number) => <Stack key={index} direction="row" justifyContent="space-between" sx={{ borderBottom: 1, borderColor: "divider", pb: 1 }}><Box><Typography fontWeight={600}>{item.act?.name ?? "chain action"}</Typography><Typography variant="caption" color="text.secondary">{item.act?.data?.quantity ?? item.block_time ?? "WAX blockchain"}</Typography></Box><Chip size="small" label={item.trx_id ? `${item.trx_id.slice(0, 8)}…` : "action"} /></Stack>) : <Typography color="text.secondary">No activity loaded yet.</Typography>}</Stack></CardContent></Card></Grid><Grid item xs={12} md={5}><Card><CardContent><Typography variant="h6">NFT gallery</Typography><Typography variant="h3" sx={{ my: 2 }}>{nfts.length}</Typography><Typography color="text.secondary">AtomicAssets held by this account</Typography><Button sx={{ mt: 2 }} component={Link} to="/nfts">View NFTs</Button></CardContent></Card></Grid></Grid>
  </Stack>;
}
