import React from "react";
import { Alert, Button, Card, CardContent, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import { buildTradeQuote, DEFAULT_SLIPPAGE_BPS, TRADING_FEE_BPS } from "../application/trading-service";
import { calculateAlcorOutput, findAlcorMarket } from "../infrastructure/alcor-market-service";
import { useDashboardStore } from "../application/dashboard-store-v2";

export function TradeScreen() {
  const { tokens, balances } = useDashboardStore();
  const [from, setFrom] = React.useState("WAX"); const [to, setTo] = React.useState("TLM"); const [amount, setAmount] = React.useState(""); const [slippage, setSlippage] = React.useState(DEFAULT_SLIPPAGE_BPS); const [quote, setQuote] = React.useState<any>(null); const [approved, setApproved] = React.useState(false); const [error, setError] = React.useState(""); const [loading, setLoading] = React.useState(false);
  const source = tokens.find((item) => item.symbol === from); const target = tokens.find((item) => item.symbol === to); const balance = balances.find((item) => item.symbol === from)?.balance?.split(" ")[0] ?? "0";
  const setPercent = (percent: number) => setAmount((Number(balance) * percent / 100).toFixed(source?.precision ?? 8));
  const review = async () => { try { if (!source || !target) throw new Error("Select supported tokens."); setLoading(true); setError(""); const market = await findAlcorMarket(source, target); const fee = (Number(amount) * TRADING_FEE_BPS / 10_000).toFixed(source.precision); const swapInput = (Number(amount) - Number(fee)).toFixed(source.precision); const output = calculateAlcorOutput(market, source, target, swapInput); setQuote(buildTradeQuote(source, target, amount, output, market.id, slippage)); setApproved(false); } catch (e) { setQuote(null); setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } };
  return <Stack spacing={2}><Card><CardContent><Stack spacing={2}><Typography variant="h5">Alcor token swap</Typography><Typography color="text.secondary">Prices come from Alcor market data. A 0.01% fee is collected by {"aurumvexilum"} and shown before approval.</Typography><Select value={from} onChange={(e) => setFrom(String(e.target.value))}>{tokens.map((item) => <MenuItem key={item.symbol} value={item.symbol}>{item.symbol}</MenuItem>)}</Select><TextField label={`Amount (${from})`} value={amount} onChange={(e) => setAmount(e.target.value)} /><Stack direction="row" spacing={1}>{[25, 50, 75, 100].map((value) => <Button key={value} size="small" variant="outlined" onClick={() => setPercent(value)}>{value === 100 ? "MAX" : `${value}%`}</Button>)}</Stack><Select value={to} onChange={(e) => setTo(String(e.target.value))}>{tokens.filter((item) => item.symbol !== from).map((item) => <MenuItem key={item.symbol} value={item.symbol}>{item.symbol}</MenuItem>)}</Select><Select value={slippage} onChange={(e) => setSlippage(Number(e.target.value))}><MenuItem value={25}>0.25% slippage</MenuItem><MenuItem value={50}>0.50% slippage</MenuItem><MenuItem value={100}>1.00% slippage</MenuItem><MenuItem value={200}>2.00% slippage</MenuItem></Select><Button variant="contained" onClick={review} disabled={loading || !amount}>{loading ? "Fetching Alcor quote…" : "Review Alcor swap"}</Button>{error && <Alert severity="error">{error}</Alert>}</Stack></CardContent></Card>{quote && <Dialog open onClose={() => setQuote(null)}><DialogTitle>Approve Alcor swap</DialogTitle><DialogContent><Stack spacing={1}><Typography>Market ID: {quote.marketId}</Typography><Typography>Input: {quote.inputAmount} {quote.from.symbol}</Typography><Typography>Swap amount: {quote.swapInputAmount} {quote.from.symbol}</Typography><Typography>Fee: {quote.feeAmount} {quote.from.symbol}</Typography><Typography>Fee recipient: {quote.feeRecipient}</Typography><Typography>Minimum received: {quote.minimumOutputAmount} {quote.to.symbol}</Typography><Typography>Slippage: {quote.slippageBps / 100}%</Typography><FormControlLabel control={<Checkbox checked={approved} onChange={(e) => setApproved(e.target.checked)} />} label="I reviewed and approve this Alcor swap" /></Stack></DialogContent><DialogActions><Button onClick={() => setQuote(null)}>Reject</Button><Button disabled={!approved} variant="contained" onClick={() => setQuote(null)}>Approve quote</Button></DialogActions></Dialog>}</Stack>;
}
